[package]
name = "path-tracing"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 2

[profile.release]
lto = true
opt-level = 3

[dependencies]
indicatif = { version = "0.17.8", features = ["rayon"] }
rand = "0.8.5"
rayon = "1.10.0"
